LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SRC_FILES := memtrack.c
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_RELATIVE_PATH := hw
LOCAL_MODULE := memtrack.$(TARGET_BOARD_PLATFORM)

include $(BUILD_SHARED_LIBRARY)